#!/bin/bash
# Скрипт для быстрой настройки Environment Variables в Vercel

echo "🔐 Настройка Environment Variables для Vercel..."
echo ""
echo "Откройте: https://vercel.com/tashflora-s-projects/goodveen/settings/environment-variables"
echo ""
echo "Добавьте следующие переменные (скопируйте каждую):"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1️⃣  DATABASE_URL"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "postgresql://postgres:U2_Fw*4uz@65~z2@db.hdqbwduzcakycshpihmp.supabase.co:5432/postgres"
echo ""
echo "2️⃣  JWT_SECRET"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "d9a69247368ed5f695c742cca33fd27691909d8ce4c6414e77bd453a5f90517a"
echo ""
echo "3️⃣  ADMIN_EMAIL"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "admin@goodveen.com"
echo ""
echo "4️⃣  ADMIN_PASSWORD"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "Tashflora26#may"
echo ""
echo "5️⃣  CORS_ORIGINS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "https://goodveen.vercel.app"
echo ""
echo "6️⃣  NODE_ENV"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "production"
echo ""
echo "7️⃣  VERCEL"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "1"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ После добавления всех переменных:"
echo "   1. Нажмите 'Save'"
echo "   2. Перейдите в Deployments → Latest → Redeploy"
echo ""
echo "🔗 Или просто сделайте git push (автодеплой)"
echo ""
